// This file is automatically created by Recurly's OpenAPI generation process
// and thus any edits you make by hand will be lost. If you wish to make a
// change to this file, please create a Github issue explaining the changes you
// need and we will usher them to the appropriate places.
package recurly

import ()

type BillingInfoVerifyCVV struct {

	// Unique security code for a credit card.
	VerificationValue *string `json:"verification_value,omitempty"`

	// An identifier for a specific payment gateway.
	GatewayCode *string `json:"gateway_code,omitempty"`

	// A token generated by Recurly.js after completing a 3-D Secure device fingerprinting or authentication challenge.
	ThreeDSecureActionResultTokenId *string `json:"three_d_secure_action_result_token_id,omitempty"`

	// A token [generated by Recurly.js](https://recurly.com/developers/reference/recurly-js/#getting-a-token).
	TokenId *string `json:"token_id,omitempty"`
}
