name: CI
on:
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    name: Go ${{ matrix.go }} tests
    strategy:
      matrix:
        go: ["1.17", "1.18", "1.19", "1.20", "1.21", "1.22", "1.23", "1.24"]
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Setup go
        uses: actions/setup-go@v6.4.0
        with:
          go-version: ${{ matrix.go }}
      - run: ./scripts/build
      - run: ./scripts/test
  buildall:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Build (matrix)
    needs: build
    steps:
      - name: Check build matrix status
        if: ${{ needs.build.result != 'success' }}
        run: exit 1
